### PR TITLE
Code Health Refactor + WP Super Cache support

### PR DESCRIPTION
**Pull request by austinheap**
Hi Imgix,

As others have noted in #1, this plugin only filters the contents of the page/post and now img tags inside the theme. Additionally, if other plugins are using output buffer control, you cannot simply hijack the outputs to run Imgix against.

This commit contains the following improvements:

1. Adds support for Imgix-ing of img URLs using 'standard' output buffering control. (Read: inside themes.)
2. Adds support for WP Super Cache, which needs to control buffers through ob_start and won't play nice with the previous change.
3. Cleans up the build process so that folders named "plugin" aren't created inside of people's Wordpress installs.
4. Contain some general code health improvements to prevent unexpected behavior.

### CODE REVIEW

**Comment by kellysutton** [comment]
Thanks for the submission, @austinheap. I'll take a peek at this shortly.

**Comment by kellysutton** [comment]
Alright, can you split this into 2 separate PRs for review? I've gone ahead and rolled in some of the cleanup you've suggested in this commit: https://github.com/imgix/imgix-wordpress/commit/f637be30301779d4a82be44172517d95f0038a26

Closing for now.

**Comment by jivamatic** [comment]
Hi Kelly, am still seeing issues when images are referenced from inside the theme and while using version 1.1.0. Do you know if this is now supported based on the commit above or should we be doing our own workarounds?

**Comment by kellysutton** [comment]
Hi @jivamatic,

Things should be better with 1.1.0, but we also have this outstanding PR with some better functionality: https://github.com/imgix/imgix-wordpress/pull/18

Can you give it a try and let me know if it solves your problems?

**Comment by jivamatic** [comment]
Hi Kelly, Thanks for the pointer. No luck with this. Looks like the theme css uses background images and other theme specific images arent being imgixified.

**Comment by wladston** [comment]
The CSS files are loaded and served independently from the Wordpress main loop. You would need to add a CSS processing capability to the plugin if you wanted it to change your CSS files. While this isn't implemented, you can just manually change your CSS files (I did that).

**Pull request closed without merging**
